INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("i", "i", 1, "i", "i");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("i", "i", 1, "i", "i");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("i", "i", 1, "i", "i");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("i", "i", 1, "i", "i");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("i", "i", 1, "i", "i");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("i", "i", 1, "i", "i");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("i", "i", 1, "i", "i");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("i", "i", 1, "i", "i");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("i", "i", 1, "i", "i");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("i", "i", 1, "i", "i");

INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);
INSERT INTO users (name, age) VALUES ("i", 1);

INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1, 1, 1);
